### ISSUE TITLE
/session_rating_forms/new: why js alert when "send"

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-counseling#95]
Fix the title. "New session rating form." Are your users computers and rails apps? They are human.
eg "Rate your Session"

Why is there a JS alert when you click send?
Is this not saving? Make it save.

**Comment by bnickodemus** [comment]
It is saving.
When the user clicks on a fill in bubble I set the class to active.
Then when the user clicks the send button, I make a ajax post and if the post was successful make an alert.

I did it this way because I didn't know how to call something like document.getElementsByClassName in Rails. 

There is probably a better way to do this but I don't know how. 
Do I need to create a new Rails class called SelectedClass or something and then style it?
